In [52]:
import numpy as np
import pandas as pd
import scipy.stats

**Problem 1**

In [3]:
SE_X_bar = 10 / np.sqrt(100)
SE_X_bar

np.float64(1.0)

In [4]:
Zscore_X_bar = (52 - 50) / SE_X_bar
Zscore_X_bar

np.float64(2.0)

At α = .10, the interval is [-1.645, 1.645], so our z score for X_bar (=2) is outside of this window. We reject the null at the 90% confidence level.  

At α = .05, the interval is [-1.960, 1.960], so our z score for X_bar (=2) is outside of this window. We reject the null at the 95% confidence level.  

At α = .01, the interval is [-2.576, 2.576], , so our z score for X_bar (=2) is within this this window. We do NOT reject the null at the 99% confidence level.

-1.960 = (x - 50) / 1

-1.960 = x - 50

'+ 50        +50 

x = 48.04, 51.96

Our confidence interval for the null, which is μ = 50, is [48.04, 51.96]. This makes sense considering that 52 is just outside of this window, and we rejected the null at the 95% confidence level by comparing z scores.

In [5]:
1.960+50

51.96

**Problem 2**

In [6]:
Zscore_S_hat = (3.1 - 0) / 1.3
Zscore_S_hat

2.3846153846153846

At α = .10, the interval is [-1.645, 1.645], so our z score for S_hat (=2.384) is outside of this window. We reject the null at the 90% confidence level.  

At α = .05, the interval is [-1.960, 1.960], so our z score for S_hat (=2.384) is outside of this window. We reject the null at the 90% confidence level.  

At α = .01, the interval is [-2.576, 2.576],  so our z score for S_hat (=2.384) is within this this window. We do NOT reject the null at the 99% confidence level.

**Problem 3**

In [7]:
SE_X_bar = 3 / 36**0.5
SE_X_bar

0.5

H0: μ = 12

-+1.960 = (x - μ) / 0.5  

* 0.5           * 0.5

-+0.98 = x - 12

+ 12        + 12

x = [11.02, 12.98]

At the 95% confidence level, our interval for μ = 12 is [11.02, 12.98]. Because X_bar = 11.5, X_bar is within this window. Therefore we do NOT reject the null hypothesis.

**Problem 4**

In [8]:
two_sample_z = (25 - 22) / np.sqrt((8**2 / 100) + (7**2 / 100))
two_sample_z

np.float64(2.822162605150792)

This two sample z score is 2.8221, which outside of the range of the 95% confidence interval under the null z-scores (-1.90, 1.960).

The 95% confidence interval representing the range of values that μA − μ B could take while still being under the null is shown below:

x represents μA − μ B:

-+1.90 = x / np.sqrt((8^2 / 100) + (7^2 / 100))

x = -+1.90 * np.sqrt((8^2 / 100) + (7^2 / 100))

x = [-2.0197, 2.0197]

So, the range of values that μA − μ B could take while still being under the null is [-2.0197, 2.0197]. Our two same z score was 2.8221, which is outside of this interval, so we reject the null. This agrees with our comparison above between the two sample z score and the 95% confidence interval z score window.

**Problem 5**

In [9]:
SE_meanA_minus_meanB = np.sqrt((6**2 / 81) + (5**2 / 64)) 
SE_meanA_minus_meanB

np.float64(0.9138213416442212)

In [10]:
zscore_meanA_minus_meanB = (14 - 12) / SE_meanA_minus_meanB
zscore_meanA_minus_meanB

np.float64(2.1886116124202553)

At the 95% confidence level, the critical z score values are [-1.960, 1.960], so because our z-score for the difference in means is 2.1886, we reject the null hypothesis.

**Problem 6**

In [11]:
SE_meanA_minus_meanB = np.sqrt((1.5**2 / 49) + (1.4**2 / 64)) 
SE_meanA_minus_meanB

np.float64(0.2766647200980616)

In [12]:
zscore_meanA_minus_meanB = (3.2 - 2.8) / SE_meanA_minus_meanB
zscore_meanA_minus_meanB

np.float64(1.4457933048283986)

At the 95% confidence level, the critical z-score values are [-1.960, 1.960]. So because our z-score for the difference in means is 1.445, we do NOT reject null hypothesis. This means that the difference in mean defect scores is not significant relative to the noise in the samples.

**Problem 7**

In [13]:
p7 = pd.read_csv('./data/ames_prices.csv')

In [14]:
p7['Central.Air'].unique()

<StringArray>
['Y', 'N']
Length: 2, dtype: str

In [15]:
air = pd.get_dummies(p7['Central.Air'], drop_first = True, dtype = int)
air

      Y
0     1
1     1
2     1
3     1
4     1
...  ..
2925  1
2926  1
2927  1
2928  1
2929  1

[2930 rows x 1 columns]

**7. A**

In [16]:
p_hat = sum(air.loc[:,'Y'])/len(air.loc[:,'Y'])
p_hat

0.9331058020477816

**7 B.**

In [ ]:
#The number of bootstrap repetitions, R, will be 5,000
R = 5_000

#The seed I used for this random number sequence is 100 
rng = np.random.default_rng(100)

#each p_hat is the bootstrap probability of a home having central air. 
p_hats = []

for x in range(R):
    boot_sample = rng.choice(air, size = len(air.loc[:,'Y']), replace = True)
    boot_p_hat = sum(boot_sample)/len(boot_sample)

    p_hats.append(boot_p_hat)

**7. C.**

In [ ]:
n = len(p_hats)
p_hat_mean = sum(p_hats)/len(p_hats)
sum_squared_diffs = sum((x - p_hat_mean)**2 for x in p_hats)

In [27]:
SE_p_hats = np.sqrt(1/(n-1) * sum_squared_diffs)
SE_p_hats

array([0.00460282])

In [28]:
#Change the output from an 1-value array to a float 
SE_p_hats = SE_p_hats[0]
SE_p_hats

np.float64(0.004602823858818426)

**7. D**

In [38]:
#p_hat is the original estimate
#SE_p_hats is the bootstrapped standard error

#90% CI:
#+/-1.645 * SE + p_hat = critical values
crit_value1 = -1.645 * SE_p_hats + p_hat
crit_value2 = 1.645 * SE_p_hats + p_hat

print(f'The 90% confidence interval for the porportion of homes that have central heating is {crit_value1.round(4)}, {crit_value2.round(4)}')

The 90% confidence interval for the porportion of homes that have central heating is 0.9255, 0.9407

In [39]:
#95% CI:
#+/-1.960 * SE + p_hat = critical values
crit_value1 = -1.960 * SE_p_hats + p_hat
crit_value2 = 1.960 * SE_p_hats + p_hat

print(f'The 95% confidence interval for the porportion of homes that have central heating is {crit_value1.round(4)}, {crit_value2.round(4)}')

The 95% confidence interval for the porportion of homes that have central heating is 0.9241, 0.9421

In [40]:
#99% CI:
#+/-2.576 * SE + p_hat = critical values
crit_value1 = -2.576 * SE_p_hats + p_hat
crit_value2 = 2.576 * SE_p_hats + p_hat

print(f'The 99% confidence interval for the porportion of homes that have central heating is {crit_value1.round(4)}, {crit_value2.round(4)}')

The 99% confidence interval for the porportion of homes that have central heating is 0.9212, 0.945

**7. E**

Given the null hypothesis that 90% of homes have central heating (i.e., H_0: p = 0.9), we:
- reject the null at the 90% confidence level (i.e., alpha = 0.1), because our confidence interval is: [0.9255, 0.9407]
- reject the null at the 95% confidence level (i.e., alpha = 0.05), because our confidence interval is: [0.9241, 0.9421]
- reject the null at the 99% confidence level (i.e., alpha = 0.01), because our confidence interval is: [0.9212, 0.945]

These results strongly suggest that the true population porportion of homes that have central air is greater than 90%, because even our widest confidence interval at alpha = 0.01 ranges from 0.9212, 0.945.

**8.**

In [48]:
area = p7.loc[:,'area']
price = p7.loc[:,'price']

In [ ]:
pearson = scipy.stats.pearsonr(np.arcsinh(area), np.arcsinh(price))
pearson[0] #I can get just the pearson correlation out by indexing the output for the first number.

np.float64(0.7231661530091357)

In [55]:
len(p7.loc[:,'area'])

2930

**8. A**

In [61]:
#The number of bootstrap repetitions, R, will be 2,000
R = 2_000

#The seed I used for this random number sequence is 100 
rng = np.random.default_rng(100)
n = len(p7.loc[:,'area'])

#To be filled in with pearson coefficients. 
pearsons = []

for x in range(R):
    boot_index = rng.choice(n, size = n, replace = True)
    boot_area = area[boot_index]
    boot_price = price[boot_index]
    boot_pearson = scipy.stats.pearsonr(np.arcsinh(boot_area), np.arcsinh(boot_price))
    pearsons.append(boot_pearson[0])

**8. B**

In [70]:
def boot_SE_calculator(bootstrap_values):
    n = len(bootstrap_values)
    mean_boot_value = sum(bootstrap_values) / n
    sum_squared_diffs = sum((x -mean_boot_value)**2 for x in bootstrap_values)
    SE_bootstrap = np.sqrt(1/(n-1) * sum_squared_diffs)
    return SE_bootstrap

In [71]:
pearsons_SE = boot_SE_calculator(pearsons)

In [72]:
print(f'the bootstrap standard error for the pearson correlation between np.arcsinh(area)and np.arcsinh(price) of houses is {boot_SE_calculator(pearsons).round(4)}')

the bootstrap standard error for the pearson correlation between np.arcsinh(area)and np.arcsinh(price) of houses is 0.0101

**8. C**

In [76]:
def normal_crit_values_calculator(estimate, standard_error):
    #90% CI:
    #+/-1.645 * SE + p_hat = critical values
    crit_value1_90 = -1.645 * standard_error + estimate
    crit_value2_90 = 1.645 * standard_error + estimate

    #95% CI:
    #+/-1.960 * SE + p_hat = critical values
    crit_value1_95 = -1.960 * standard_error + estimate
    crit_value2_95 = 1.960 * standard_error + estimate

    #99% CI:
    #+/-2.576 * SE + p_hat = critical values
    crit_value1_99 = -2.576 * standard_error + estimate
    crit_value2_99 = 2.576 * standard_error + estimate

    print(f'The 90% confidence interval is {crit_value1_90.round(4)}, {crit_value2_90.round(4)}')
    print(f'The 95% confidence interval is {crit_value1_95.round(4)}, {crit_value2_95.round(4)}')
    print(f'The 99% confidence interval is {crit_value1_99.round(4)}, {crit_value2_99.round(4)}')

In [77]:
normal_crit_values_calculator(pearson[0], pearsons_SE)

The 90% confidence interval is 0.7065, 0.7398
The 95% confidence interval is 0.7033, 0.743
The 99% confidence interval is 0.6971, 0.7493

Given the null hypothesis that the area of a home is NOT correlated with the price of a home (i.e., H_0: the peason correlation = 0), we reject the null hypothesis at the alpha = 0.1, 0.05, and 0.01 values, because the confidence interval for each of these alphas does not contain 0. 

In other words, this strongly suggests that the price and the area of a home are correlated, and that they are relatively strongly correlated. For instance, our 99% confidence interval for pearson correlation is [0.6971, 0.7493]. While this does not mean that the price of the home is determined by area, it does mean that homes with higher area tend to also have higher prices.

**8. E.**

For any given row, the area and the price both refer to the area and price of the same house. We need to keep area and price paired together during resampling so that we keep the price of a house associated with the area of that house. If we do not keep that association, our data will become meaningless. 

I did this by bootstrapping the row index, and then using the bootstrapped row index to pull corresponding area and price observations for each bootstrapped house. Then, I computed the pearson correlation.

**9.**

In [78]:
cancer = pd.read_csv('./data/metabric.csv')

In [80]:
survival = cancer[['Overall Survival (Months)', 'Overall Survival Status']]

In [ ]:
survival
#Looks like a the last reported check-in is reported as overall survival time for a patient who is still living.

      Overall Survival (Months) Overall Survival Status
0                     84.633333                0:LIVING
1                    163.700000              1:DECEASED
2                    164.933333                0:LIVING
3                     41.366667              1:DECEASED
4                      7.800000              1:DECEASED
...                         ...                     ...
1338                 201.166667                0:LIVING
1339                 105.200000              1:DECEASED
1340                 200.333333                0:LIVING
1341                  14.700000              1:DECEASED
1342                 281.500000                0:LIVING

[1343 rows x 2 columns]

In [82]:
time = survival['Overall Survival (Months)']

**9. A**

In [86]:
def my_bootstrapper(data):
    '''Gonna make a bootstrap function for myself. 'data' should be in list form for this function. Will return a list of the mean result for each bootstrap iteration.'''
    n = len(data)
    R = 2_000
    rng = np.random.default_rng(100)
    boot_outputs = []

    for x in range(R):
        boot_result = rng.choice(data, size = n, replace = True)
        boot_mean = sum(boot_result) / n
        boot_outputs.append(boot_mean)

    return boot_outputs

In [88]:
time_boot = my_bootstrapper(time)

I wrote a function for this step, and the function uses 2,000 bootstrap iterations with a random number seed of 100.

**9. B**

In [91]:
time_SE = boot_SE_calculator(time_boot)

In [92]:
print(f'the standard error for the bootstrapped average survival time is {time_SE.round(4)}')

the standard error for the bootstrapped average survival time is 2.089

**9. C**

In [95]:
mean_survival_time = sum(time) / len(time)
mean_survival_time

129.09429138744105

In [94]:
normal_crit_values_calculator(mean_survival_time, time_SE)

The 90% confidence interval is 125.6579, 132.5307
The 95% confidence interval is 124.9998, 133.1887
The 99% confidence interval is 123.713, 134.4756

**9. D.**

Given the null hypothesis that the average survival time for a cancer treatment patient is 120 months (i.e. H_0: mean = 120), we reject the null at the 90%, 95%, and 99% confidence intervals. Given that our 99% interval is [123.713, 134.4756], we anticipate the true survival time to be greater than 120 months.

**9. E.**

Our estimated survival time was  129.09 months (roughly 10.7 years), and our 95% confidence interval was [124.9998, 133.1887] (roughly 10 to 11 years). Importantly, not all of the patients are dead! We do not know how long they lived, because they were still living at the time of last contact. The survey reported their survival time to-date, but they continued living for some unknown time thereafter. 

For this reason, our results do not estimate unrestricted mean lifetime because the survey has not run long enough for all the patients to die out. We only have the death dates of the shortest-lived patients in the survey, whereas the longest-lived patients are still accruing unreported survival time.

**10**

In [105]:
nhanes = pd.read_csv('./data/nhanes_data_17_18.csv')

C:\Users\hmrif\AppData\Local\Temp\ipykernel_20216\904120397.py:1: DtypeWarning: Columns (0: ServedActiveDutyInUsArmedForces) have mixed types. Specify dtype option on import or set low_memory=False.
  nhanes = pd.read_csv('./data/nhanes_data_17_18.csv')

In [118]:
age_sleep = nhanes[['AgeInYearsAtScreening','SleepHoursWeekdaysOrWorkdays']][nhanes['AgeInYearsAtScreening'] >= 18] #and nhanes['SleepHoursWeekdaysOrWorkdays'] is not NaN]
age_sleep

      AgeInYearsAtScreening  SleepHoursWeekdaysOrWorkdays
2                      66.0                           8.0
3                      18.0                          10.5
5                      66.0                           8.0
6                      75.0                           7.0
7                      56.0                           7.0
...                     ...                           ...
8359                   33.0                           6.5
8361                   70.0                           8.5
8362                   42.0                           6.0
8363                   41.0                           8.0
8365                   38.0                           8.0

[5533 rows x 2 columns]

In [116]:
age_sleep.isna().any(axis = None)

np.True_

In [119]:
age_sleep = age_sleep.dropna()

In [120]:
age_sleep

      AgeInYearsAtScreening  SleepHoursWeekdaysOrWorkdays
2                      66.0                           8.0
3                      18.0                          10.5
5                      66.0                           8.0
6                      75.0                           7.0
7                      56.0                           7.0
...                     ...                           ...
8359                   33.0                           6.5
8361                   70.0                           8.5
8362                   42.0                           6.0
8363                   41.0                           8.0
8365                   38.0                           8.0

[5489 rows x 2 columns]

In [122]:
mean_sleep_hours = sum(age_sleep['SleepHoursWeekdaysOrWorkdays']) / len(age_sleep['SleepHoursWeekdaysOrWorkdays'])
mean_sleep_hours

7.62124248496994

**10. A**

In [ ]:
#2,000 repetitions with seed = 100.
boot_sleep_hours = my_bootstrapper(age_sleep['SleepHoursWeekdaysOrWorkdays'])

In [124]:
boot_sleep_hours

[np.float64(7.602842047731827),
 np.float64(7.621880123884132),
 np.float64(7.673346693386773),
 np.float64(7.619329568227363),
 np.float64(7.670978320276918),
 np.float64(7.656950264164693),
 np.float64(7.635908179996356),
 np.float64(7.591182364729459),
 np.float64(7.62260885407178),
 np.float64(7.625159409728548),
 np.float64(7.633175441792676),
 np.float64(7.658043359446165),
 np.float64(7.583621789032611),
 np.float64(7.625523774822372),
 np.float64(7.610766988522499),
 np.float64(7.618145381672436),
 np.float64(7.632355620331572),
 np.float64(7.587903078885043),
 np.float64(7.624977227181636),
 np.float64(7.619329568227363),
 np.float64(7.6164146474767715),
 np.float64(7.61942065950082),
 np.float64(7.61441063946074),
 np.float64(7.629076334487156),
 np.float64(7.632355620331572),
 np.float64(7.628256513026052),
 np.float64(7.587994170158499),
 np.float64(7.623428675532884),
 np.float64(7.658134450719621),
 np.float64(7.644652942248133),
 np.float64(7.625523774822372),
 np.float64(7.590180360721443),
 np.float64(7.622973219165604),
 np.float64(7.629531790854436),
 np.float64(7.654399708507925),
 np.float64(7.599744944434323),
 np.float64(7.609947167061396),
 np.float64(7.6014756786299875),
 np.float64(7.595828019675715),
 np.float64(7.632082346511204),
 np.float64(7.602933139005283),
 np.float64(7.6275277828384045),
 np.float64(7.6027509564583715),
 np.float64(7.6014756786299875),
 np.float64(7.631444707597012),
 np.float64(7.629167425760612),
 np.float64(7.581253415922754),
 np.float64(7.62716341774458),
 np.float64(7.615230460921843),
 np.float64(7.592822007651667),
 np.float64(7.599927126981235),
 np.float64(7.630260521042084),
 np.float64(7.644926216068501),
 np.float64(7.632264529058117),
 np.float64(7.6227910366186915),
 np.float64(7.625979231189652),
 np.float64(7.61213335762434),
 np.float64(7.610038258334852),
 np.float64(7.607760976498452),
 np.float64(7.642375660411733),
 np.float64(7.603661869192932),
 np.float64(7.660593915102933),
 np.float64(7.624339588267444),
 np.float64(7.614957187101476),
 np.float64(7.596374567316451),
 np.float64(7.630898159956276),
 np.float64(7.602842047731827),
 np.float64(7.583895062852979),
 np.float64(7.619693933321188),
 np.float64(7.588722900346147),
 np.float64(7.593095281472035),
 np.float64(7.609218436873747),
 np.float64(7.622062306431044),
 np.float64(7.606121333576243),
 np.float64(7.599107305520131),
 np.float64(7.605119329568227),
 np.float64(7.641920204044452),
 np.float64(7.591637821096739),
 np.float64(7.6072144288577155),
 np.float64(7.642648934232101),
 np.float64(7.628347604299508),
 np.float64(7.649389688467845),
 np.float64(7.595736928402259),
 np.float64(7.627801056658772),
 np.float64(7.613226452905812),
 np.float64(7.630624886135908),
 np.float64(7.595099289488067),
 np.float64(7.61122244488978),
 np.float64(7.628711969393332),
 np.float64(7.627892147932228),
 np.float64(7.633539806886501),
 np.float64(7.62488613590818),
 np.float64(7.594006194206595),
 np.float64(7.607487702678084),
 np.float64(7.646839132811077),
 np.float64(7.62397522317362),
 np.float64(7.652213517944981),
 np.float64(7.645290581162325),
 np.float64(7.653762069593733),
 np.float64(7.600473674621972),
 np.float64(7.6091273456002915),
 np.float64(7.611860083803972),
 np.float64(7.600746948442339),
 np.float64(7.633813080706869),
 np.float64(7.619056294406996),
 np.float64(7.634359628347604),
 np.float64(7.655401712515941),
 np.float64(7.582801967571506),
 np.float64(7.605665877208963),
 np.float64(7.631080342503188),
 np.float64(7.598105301512115),
 np.float64(7.62989615594826),
 np.float64(7.622973219165604),
 np.float64(7.647203497904901),
 np.float64(7.603661869192932),
 np.float64(7.588996174166515),
 np.float64(7.657861176899253),
 np.float64(7.610858079795956),
 np.float64(7.623793040626708),
 np.float64(7.592548733831299),
 np.float64(7.595463654581891),
 np.float64(7.6091273456002915),
 np.float64(7.593186372745491),
 np.float64(7.600929130989251),
 np.float64(7.615048278374932),
 np.float64(7.627983239205684),
 np.float64(7.633813080706869),
 np.float64(7.609036254326836),
 np.float64(7.62716341774458),
 np.float64(7.596101293496083),
 np.float64(7.612862087811988),
 np.float64(7.632355620331572),
 np.float64(7.6008380397157955),
 np.float64(7.61714337766442),
 np.float64(7.639825104754965),
 np.float64(7.598196392785571),
 np.float64(7.632355620331572),
 np.float64(7.6116779012570595),
 np.float64(7.62260885407178),
 np.float64(7.622062306431044),
 np.float64(7.597467662597923),
 np.float64(7.620513754782292),
 np.float64(7.600018218254691),
 np.float64(7.603844051739843),
 np.float64(7.598105301512115),
 np.float64(7.6275277828384045),
 np.float64(7.62534159227546),
 np.float64(7.637001275277829),
 np.float64(7.615685917289124),
 np.float64(7.634723993441428),
 np.float64(7.6501184186554925),
 np.float64(7.633539806886501),
 np.float64(7.604846055747859),
 np.float64(7.662506831845509),
 np.float64(7.6227910366186915),
 np.float64(7.640827108762981),
 np.float64(7.623155401712516),
 np.float64(7.604390599380579),
 np.float64(7.592002186190563),
 np.float64(7.657952268172709),
 np.float64(7.645837128803061),
 np.float64(7.605665877208963),
 np.float64(7.5881763527054105),
 np.float64(7.614046274366916),
 np.float64(7.645746037529604),
 np.float64(7.646019311349972),
 np.float64(7.644926216068501),
 np.float64(7.625705957369284),
 np.float64(7.583530697759155),
 np.float64(7.6526689743122605),
 np.float64(7.638367644379668),
 np.float64(7.594734924394243),
 np.float64(7.638367644379668),
 np.float64(7.622244488977956),
 np.float64(7.63080706868282),
 np.float64(7.626799052650756),
 np.float64(7.6424667516851885),
 np.float64(7.62306431043906),
 np.float64(7.610038258334852),
 np.float64(7.621424667516852),
 np.float64(7.6189652031335395),
 np.float64(7.606758972490435),
 np.float64(7.596010202222627),
 np.float64(7.605574785935508),
 np.float64(7.641920204044452),
 np.float64(7.632264529058117),
 np.float64(7.599016214246675),
 np.float64(7.647385680451813),
 np.float64(7.625705957369284),
 np.float64(7.62124248496994),
 np.float64(7.62488613590818),
 np.float64(7.611951175077428),
 np.float64(7.597923118965203),
 np.float64(7.601657861176899),
 np.float64(7.6227910366186915),
 np.float64(7.615685917289124),
 np.float64(7.609673893241028),
 np.float64(7.593095281472035),
 np.float64(7.581253415922754),
 np.float64(7.628438695572964),
 np.float64(7.574877026780834),
 np.float64(7.61031153215522),
 np.float64(7.641738021497541),
 np.float64(7.648934232100565),
 np.float64(7.6507560575696845),
 np.float64(7.619693933321188),
 np.float64(7.5900892694479865),
 np.float64(7.636363636363637),
 np.float64(7.6244306795409),
 np.float64(7.631171433776644),
 np.float64(7.591820003643651),
 np.float64(7.591364547276371),
 np.float64(7.621971215157588),
 np.float64(7.600746948442339),
 np.float64(7.656768081617781),
 np.float64(7.61942065950082),
 np.float64(7.629258517034068),
 np.float64(7.616779012570595),
 np.float64(7.625979231189652),
 np.float64(7.608307524139187),
 np.float64(7.630351612315541),
 np.float64(7.591000182182547),
 np.float64(7.593915102933139),
 np.float64(7.618236472945892),
 np.float64(7.615139369648388),
 np.float64(7.609673893241028),
 np.float64(7.613408635452724),
 np.float64(7.613226452905812),
 np.float64(7.617234468937876),
 np.float64(7.620422663508836),
 np.float64(7.617872107852068),
 np.float64(7.659409728548005),
 np.float64(7.610038258334852),
 np.float64(7.632264529058117),
 np.float64(7.638732009473492),
 np.float64(7.652486791765349),
 np.float64(7.63718345782474),
 np.float64(7.600109309528147),
 np.float64(7.642831116779012),
 np.float64(7.6008380397157955),
 np.float64(7.605756968482419),
 np.float64(7.599836035707779),
 np.float64(7.657496811805429),
 np.float64(7.62169794133722),
 np.float64(7.63217343778466),
 np.float64(7.596283476042995),
 np.float64(7.641920204044452),
 np.float64(7.6418291127709965),
 np.float64(7.646839132811077),
 np.float64(7.581253415922754),
 np.float64(7.622426671524868),
 np.float64(7.599380579340499),
 np.float64(7.612406631444707),
 np.float64(7.615230460921843),
 np.float64(7.60940061942066),
 np.float64(7.618418655492804),
 np.float64(7.631626890143925),
 np.float64(7.651029331390053),
 np.float64(7.648752049553653),
 np.float64(7.6666059391510295),
 np.float64(7.650573875022773),
 np.float64(7.600473674621972),
 np.float64(7.672253598105302),
 np.float64(7.63217343778466),
 np.float64(7.599471670613955),
 np.float64(7.612770996538532),
 np.float64(7.633357624339588),
 np.float64(7.598834031699763),
 np.float64(7.613955183093459),
 np.float64(7.618054290398979),
 np.float64(7.601566769903443),
 np.float64(7.5881763527054105),
 np.float64(7.654946256148661),
 np.float64(7.637274549098197),
 np.float64(7.676261614137366),
 np.float64(7.6312625250501),
 np.float64(7.623246492985972),
 np.float64(7.645199489888869),
 np.float64(7.654035343414101),
 np.float64(7.644197485880853),
 np.float64(7.631171433776644),
 np.float64(7.623701949353252),
 np.float64(7.596647841136819),
 np.float64(7.6319912552377485),
 np.float64(7.62579704864274),
 np.float64(7.617963199125524),
 np.float64(7.614592822007651),
 np.float64(7.612224448897796),
 np.float64(7.640280561122244),
 np.float64(7.638458735653124),
 np.float64(7.587083257423939),
 np.float64(7.588631809072691),
 np.float64(7.661869192931317),
 np.float64(7.63718345782474),
 np.float64(7.62033157223538),
 np.float64(7.62124248496994),
 np.float64(7.649571871014757),
 np.float64(7.578065221351794),
 np.float64(7.615868099836035),
 np.float64(7.624977227181636),
 np.float64(7.6104026234286755),
 np.float64(7.591546729823283),
 np.float64(7.680633995263253),
 np.float64(7.6002004008016035),
 np.float64(7.589542721807251),
 np.float64(7.599744944434323),
 np.float64(7.647841136819093),
 np.float64(7.649754053561669),
 np.float64(7.58316633266533),
 np.float64(7.578976134086354),
 np.float64(7.634632902167972),
 np.float64(7.624066314447076),
 np.float64(7.643833120787028),
 np.float64(7.599107305520131),
 np.float64(7.569775915467298),
 np.float64(7.658225541993077),
 np.float64(7.635999271269812),
 np.float64(7.6411914738568045),
 np.float64(7.60803425031882),
 np.float64(7.644561850974677),
 np.float64(7.63171798141738),
 np.float64(7.595190380761523),
 np.float64(7.623610858079796),
 np.float64(7.62260885407178),
 np.float64(7.61668792129714),
 np.float64(7.617872107852068),
 np.float64(7.629622882127892),
 np.float64(7.576881034796866),
 np.float64(7.637092366551284),
 np.float64(7.657770085625797),
 np.float64(7.590271451994899),
 np.float64(7.596556749863363),
 np.float64(7.622244488977956),
 np.float64(7.633357624339588),
 np.float64(7.60803425031882),
 np.float64(7.6319912552377485),
 np.float64(7.605756968482419),
 np.float64(7.5995627618874115),
 np.float64(7.574421570413555),
 np.float64(7.633630898159956),
 np.float64(7.6153215521953),
 np.float64(7.601566769903443),
 np.float64(7.614046274366916),
 np.float64(7.610220440881764),
 np.float64(7.634177445800693),
 np.float64(7.582619785024595),
 np.float64(7.611495718710148),
 np.float64(7.636090362543269),
 np.float64(7.6170522863909635),
 np.float64(7.614866095828019),
 np.float64(7.610038258334852),
 np.float64(7.6084897066860995),
 np.float64(7.629805064674804),
 np.float64(7.668609947167061),
 np.float64(7.6170522863909635),
 np.float64(7.62534159227546),
 np.float64(7.6339041719803244),
 np.float64(7.599653853160867),
 np.float64(7.626343596283476),
 np.float64(7.622699945345236),
 np.float64(7.604572781927492),
 np.float64(7.61441063946074),
 np.float64(7.6196028420477315),
 np.float64(7.637456731645108),
 np.float64(7.6437420295135725),
 np.float64(7.633630898159956),
 np.float64(7.5894516305337945),
 np.float64(7.600382583348515),
 np.float64(7.636181453816724),
 np.float64(7.624795044634724),
 np.float64(7.640918200036436),
 np.float64(7.6475678629987245),
 np.float64(7.5989251229732195),
 np.float64(7.624521770814356),
 np.float64(7.6072144288577155),
 np.float64(7.6268901439242125),
 np.float64(7.632719985425396),
 np.float64(7.634815084714885),
 np.float64(7.60302423027874),
 np.float64(7.653853160867189),
 np.float64(7.624248496993988),
 np.float64(7.626161413736564),
 np.float64(7.60712333758426),
 np.float64(7.635270541082164),
 np.float64(7.663053379486246),
 np.float64(7.61258881399162),
 np.float64(7.609673893241028),
 np.float64(7.609491710694115),
 np.float64(7.6268901439242125),
 np.float64(7.6482055019129165),
 np.float64(7.639642922208052),
 np.float64(7.611860083803972),
 np.float64(7.61031153215522),
 np.float64(7.593824011659683),
 np.float64(7.6380943705593),
 np.float64(7.62033157223538),
 np.float64(7.626525778830388),
 np.float64(7.608854071779923),
 np.float64(7.628620878119876),
 np.float64(7.595372563308435),
 np.float64(7.611131353616323),
 np.float64(7.619147385680452),
 np.float64(7.609856075787939),
 np.float64(7.604117325560211),
 np.float64(7.6300783384951725),
 np.float64(7.6202404809619235),
 np.float64(7.632993259245764),
 np.float64(7.6513936964838765),
 np.float64(7.624157405720532),
 np.float64(7.607032246310803),
 np.float64(7.613864091820004),
 np.float64(7.606667881216979),
 np.float64(7.62989615594826),
 np.float64(7.6424667516851885),
 np.float64(7.568865002732738),
 np.float64(7.653670978320277),
 np.float64(7.6392785571142285),
 np.float64(7.677627983239206),
 np.float64(7.619056294406996),
 np.float64(7.628711969393332),
 np.float64(7.6021133175441795),
 np.float64(7.601566769903443),
 np.float64(7.647112406631445),
 np.float64(7.616779012570595),
 np.float64(7.6281654217525965),
 np.float64(7.599653853160867),
 np.float64(7.589633813080707),
 np.float64(7.6411914738568045),
 np.float64(7.678083439606485),
 np.float64(7.604390599380579),
 np.float64(7.652122426671525),
 np.float64(7.619967207141555),
 np.float64(7.603752960466387),
 np.float64(7.593550737839315),
 np.float64(7.633721989433412),
 np.float64(7.648023319366005),
 np.float64(7.656585899070869),
 np.float64(7.548005101111314),
 np.float64(7.6602295500091095),
 np.float64(7.619785024594644),
 np.float64(7.601566769903443),
 np.float64(7.64447075970122),
 np.float64(7.623701949353252),
 np.float64(7.645199489888869),
 np.float64(7.644744033521588),
 np.float64(7.6153215521953),
 np.float64(7.6339041719803244),
 np.float64(7.596192384769539),
 np.float64(7.614228456913827),
 np.float64(7.606941155037347),
 np.float64(7.643924212060485),
 np.float64(7.605574785935508),
 np.float64(7.602477682638003),
 np.float64(7.62351976680634),
 np.float64(7.580615777008562),
 np.float64(7.598560757879395),
 np.float64(7.563763891419202),
 np.float64(7.6520313353980685),
 np.float64(7.625250501002004),
 np.float64(7.6084897066860995),
 np.float64(7.62625250501002),
 np.float64(7.630624886135908),
 np.float64(7.659136454727637),
 np.float64(7.63536163235562),
 np.float64(7.590453634541811),
 np.float64(7.626343596283476),
 np.float64(7.646748041537621),
 np.float64(7.634997267261796),
 np.float64(7.6059391510293315),
 np.float64(7.612679905265075),
 np.float64(7.598651849152851),
 np.float64(7.634359628347604),
 np.float64(7.559664784113682),
 np.float64(7.6175988340317),
 np.float64(7.638914192020405),
 np.float64(7.6227910366186915),
 np.float64(7.6288030606667885),
 np.float64(7.624157405720532),
 np.float64(7.5995627618874115),
 np.float64(7.656130442703589),
 np.float64(7.649662962288213),
 np.float64(7.611404627436691),
 np.float64(7.656403716523957),
 np.float64(7.6059391510293315),
 np.float64(7.598651849152851),
 np.float64(7.624066314447076),
 np.float64(7.630989251229733),
 np.float64(7.619693933321188),
 np.float64(7.598469666605939),
 np.float64(7.602659865184915),
 np.float64(7.635270541082164),
 np.float64(7.617507742758244),
 np.float64(7.606850063763892),
 np.float64(7.6332665330661325),
 np.float64(7.654946256148661),
 np.float64(7.627983239205684),
 np.float64(7.55993805793405),
 np.float64(7.614866095828019),
 np.float64(7.624977227181636),
 np.float64(7.6437420295135725),
 np.float64(7.604481690654035),
 np.float64(7.60302423027874),
 np.float64(7.5888139916196025),
 np.float64(7.590817999635635),
 np.float64(7.608125341592276),
 np.float64(7.627254509018036),
 np.float64(7.642831116779012),
 np.float64(7.610949171069412),
 np.float64(7.596374567316451),
 np.float64(7.601657861176899),
 np.float64(7.623155401712516),
 np.float64(7.605848059755876),
 np.float64(7.60940061942066),
 np.float64(7.645837128803061),
 np.float64(7.649298597194389),
 np.float64(7.627345600291492),
 np.float64(7.648114410639461),
 np.float64(7.629622882127892),
 np.float64(7.60940061942066),
 np.float64(7.623246492985972),
 np.float64(7.640736017489525),
 np.float64(7.626434687556932),
 np.float64(7.613864091820004),
 np.float64(7.636636910184005),
 np.float64(7.613864091820004),
 np.float64(7.584532701767171),
 np.float64(7.648934232100565),
 np.float64(7.63490617598834),
 np.float64(7.612679905265075),
 np.float64(7.575514665695026),
 np.float64(7.6469302240845325),
 np.float64(7.6002004008016035),
 np.float64(7.652942248132629),
 np.float64(7.601566769903443),
 np.float64(7.672617963199126),
 np.float64(7.613864091820004),
 np.float64(7.656130442703589),
 np.float64(7.647658954272181),
 np.float64(7.648023319366005),
 np.float64(7.585261431954819),
 np.float64(7.624157405720532),
 np.float64(7.631900163964292),
 np.float64(7.63627254509018),
 np.float64(7.636181453816724),
 np.float64(7.634815084714885),
 np.float64(7.660320641282565),
 np.float64(7.60712333758426),
 np.float64(7.631444707597012),
 np.float64(7.648387684459829),
 np.float64(7.629349608307524),
 np.float64(7.613408635452724),
 np.float64(7.645837128803061),
 np.float64(7.624703953361268),
 np.float64(7.653033339406085),
 np.float64(7.599653853160867),
 np.float64(7.634268537074148),
 np.float64(7.6380032792858445),
 np.float64(7.601931134997267),
 np.float64(7.592002186190563),
 np.float64(7.615503734742211),
 np.float64(7.6526689743122605),
 np.float64(7.640918200036436),
 np.float64(7.607669885224995),
 np.float64(7.620969211149572),
 np.float64(7.63718345782474),
 np.float64(7.6640553834942615),
 np.float64(7.638823100746948),
 np.float64(7.632993259245764),
 np.float64(7.6215157587903075),
 np.float64(7.591637821096739),
 np.float64(7.605756968482419),
 np.float64(7.591455638549827),
 np.float64(7.6319912552377485),
 np.float64(7.654946256148661),
 np.float64(7.60940061942066),
 np.float64(7.64447075970122),
 np.float64(7.617963199125524),
 np.float64(7.598014210238659),
 np.float64(7.621424667516852),
 np.float64(7.6602295500091095),
 np.float64(7.664510839861541),
 np.float64(7.607032246310803),
 np.float64(7.6326288941519405),
 np.float64(7.62397522317362),
 np.float64(7.604572781927492),
 np.float64(7.601931134997267),
 np.float64(7.6399161960284205),
 np.float64(7.608671889233012),
 np.float64(7.588085261431955),
 np.float64(7.608854071779923),
 np.float64(7.617416651484787),
 np.float64(7.6091273456002915),
 np.float64(7.6405538349426125),
 np.float64(7.617416651484787),
 np.float64(7.640736017489525),
 np.float64(7.63900528329386),
 np.float64(7.631444707597012),
 np.float64(7.610766988522499),
 np.float64(7.624066314447076),
 np.float64(7.611495718710148),
 np.float64(7.6373656403716526),
 np.float64(7.57906722535981),
 np.float64(7.630989251229733),
 np.float64(7.634359628347604),
 np.float64(7.609673893241028),
 np.float64(7.601748952450356),
 np.float64(7.657587903078885),
 np.float64(7.647021315357989),
 np.float64(7.622973219165604),
 np.float64(7.583803971579522),
 np.float64(7.6267079613773),
 np.float64(7.578976134086354),
 np.float64(7.590544725815267),
 np.float64(7.643286573146293),
 np.float64(7.620422663508836),
 np.float64(7.650482783749317),
 np.float64(7.636090362543269),
 np.float64(7.609036254326836),
 np.float64(7.620058298415012),
 np.float64(7.631626890143925),
 np.float64(7.6507560575696845),
 np.float64(7.590544725815267),
 np.float64(7.656403716523957),
 np.float64(7.63536163235562),

**10. B**

In [125]:
sleep_SE = boot_SE_calculator(boot_sleep_hours)

In [126]:
print(f'the standard error for the bootstrapped average sleep time (in hours) is {sleep_SE.round(4)}')

the standard error for the bootstrapped average sleep time (in hours) is 0.0222

**10. C.**

In [127]:
normal_crit_values_calculator(mean_sleep_hours, sleep_SE)

The 90% confidence interval is 7.5847, 7.6577
The 95% confidence interval is 7.5778, 7.6647
The 99% confidence interval is 7.5641, 7.6784

**10. D.**

Given the null hypothesis that the population sleeps 8 hours a night on average, we reject the null at the 90%, 95%, and 99% confidence levels.

**10. E**

In terms of statistical significance, the interval is very narrow even at the 99% confidence level, with only 0.11 hours width. This is because the sample is very large. Since our interval is entirely above 7 hours but below 8, we have strong evidence that the mean sleep duration exceeeds 7 hours, but does not reach 8.

In terms of practical significance, we cannot use this confidence interval to learn much else about sleep. For example, we do not know how sleep times are distributed in our sample, so we cannot estimate the density of sleep times for the population. It could be quite useful to know whether many people sleep much less than 7 hours, but we cannot determine that from just this confidence interval.